name: CI/CD Pipeline (Front-end)

on:
  push:
    branches:
      - main
    paths:
      - 'front-end/**'

  pull_request:
    branches:
      - main
    paths:
      - 'front-end/**'

env:
  IMAGE_NAME: "leonildolinck/nginx-frontend"
  IMAGE_TAG: "latest"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: ./front-end
      - run: npm run lint
        working-directory: ./front-end

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        working-directory: ./front-end
      - run: npm run test -- --watch=false
        working-directory: ./front-end
      - run: npm run test:coverage
        working-directory: ./front-end

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./front-end

      - name: Push Docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to GCP Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push' && github.ref_name == 'main'
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform -chdir=front-end/infra init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

      - name: Terraform Validate
        id: validate
        run: terraform -chdir=front-end/infra validate
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terraform Apply
        id: apply
        run: terraform -chdir=front-end/infra apply -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          TF_VAR_docker_image_name: ${{ env.DOCKER_IMAGE_NAME }}
          TF_VAR_docker_image_tag: ${{ env.DOCKER_IMAGE_TAG }}
